name: Build & Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 */7 * *'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install libboost-system-dev libmariadb-dev-compat socat

    - name: Configure CMake
      run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTEST_EXTENDED_ENABLED=ON ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --parallel 6
        cmake --build . --parallel 6 --target test_odr

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
